# Generated by Django 4.2.23 on 2025-07-20 08:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MechanicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "government_id",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="mechanic/ids/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanic_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "mechanic profile",
                "verbose_name_plural": "mechanic profiles",
            },
        ),
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.CharField(max_length=255)),
                (
                    "government_id",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="driver/ids/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "driver_license",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="driver/licenses/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("car", "Car"),
                            ("motorcycle", "Motorcycle"),
                            ("van", "Van"),
                            ("truck", "Truck"),
                            ("bicycle", "Bicycle"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "vehicle_registration_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "vehicle_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="driver/vehicle_photos/"
                    ),
                ),
                (
                    "insurance_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="driver/insurance/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "driver profile",
                "verbose_name_plural": "driver profiles",
            },
        ),
        migrations.CreateModel(
            name="MerchantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cac_number", models.CharField(max_length=100)),
                ("business_address", models.CharField(max_length=255)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="merchant/profile_pics/"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "merchant profile",
                "verbose_name_plural": "merchant profiles",
                "indexes": [
                    models.Index(
                        fields=["user"], name="users_merch_user_id_692808_idx"
                    ),
                    models.Index(
                        fields=["cac_number"], name="users_merch_cac_num_072905_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="users_merch_created_ae921f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MechanicReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mechanic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="users.mechanicprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanic_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["mechanic"], name="users_mecha_mechani_3c2d98_idx"
                    ),
                    models.Index(
                        fields=["user"], name="users_mecha_user_id_7819bb_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="users_mecha_created_031801_idx"
                    ),
                ],
                "unique_together": {("mechanic", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="mechanicprofile",
            index=models.Index(fields=["user"], name="users_mecha_user_id_40bd9f_idx"),
        ),
        migrations.AddIndex(
            model_name="mechanicprofile",
            index=models.Index(
                fields=["is_approved"], name="users_mecha_is_appr_93e7b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mechanicprofile",
            index=models.Index(
                fields=["created_at"], name="users_mecha_created_1aac50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driverprofile",
            index=models.Index(fields=["user"], name="users_drive_user_id_7d2bc3_idx"),
        ),
        migrations.AddIndex(
            model_name="driverprofile",
            index=models.Index(
                fields=["phone_number"], name="users_drive_phone_n_e0538e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driverprofile",
            index=models.Index(
                fields=["is_approved"], name="users_drive_is_appr_200e56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driverprofile",
            index=models.Index(
                fields=["created_at"], name="users_drive_created_bcfe0b_idx"
            ),
        ),
    ]
