# Generated by Django 4.2.23 on 2025-07-20 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_mechanicprofile_driverprofile_merchantprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="users.driverprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["driver"], name="users_drive_driver__7f9bb2_idx"
                    ),
                    models.Index(
                        fields=["user"], name="users_drive_user_id_fbefcc_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="users_drive_created_a6a6ed_idx"
                    ),
                ],
                "unique_together": {("driver", "user")},
            },
        ),
    ]
