# Generated by Django 4.2.23 on 2025-07-24 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_driverprofile_latitude_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "wallet",
                "verbose_name_plural": "wallets",
            },
        ),
    ]
