# Generated by Django 4.2.23 on 2025-07-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_wallet_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantprofile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
