# Generated by Django 4.2.23 on 2025-08-03 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0007_alter_ride_distance_km_alter_ride_duration_min"),
        ("users", "0007_merchantprofile_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="current_ride",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_driver",
                to="rides.ride",
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="last_location_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="last_online",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="license_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="total_earnings",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="total_rides",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_info",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_plate",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="driverprofile",
            index=models.Index(
                fields=["is_available"], name="users_drive_is_avai_b45cfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driverprofile",
            index=models.Index(
                fields=["is_online"], name="users_drive_is_onli_0158ee_idx"
            ),
        ),
    ]
