# Generated by Django 4.2.23 on 2025-08-03 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_driverprofile_current_ride_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=20)),
                ("account_name", models.CharField(max_length=255)),
                ("bank_code", models.CharField(max_length=10)),
                ("bank_name", models.CharField(max_length=255)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "paystack_recipient_code",
                    models.CharField(
                        blank=True,
                        help_text="Paystack recipient code for transfers",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "bank account",
                "verbose_name_plural": "bank accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="fee",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Transaction fee", max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional transaction metadata"
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="daily_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=100000.0,
                help_text="Daily transaction limit",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="monthly_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=1000000.0,
                help_text="Monthly transaction limit",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                    ("refund", "Refund"),
                    ("withdrawal", "Withdrawal"),
                    ("deposit", "Deposit"),
                    ("payment", "Payment"),
                    ("top_up", "Top Up"),
                    ("transfer", "Transfer"),
                    ("fee", "Fee"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="users_trans_status_efc2db_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["reference"], name="users_trans_referen_b3fb6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["is_active"], name="users_walle_is_acti_d94603_idx"
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(fields=["user"], name="users_banka_user_id_54588a_idx"),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["is_verified"], name="users_banka_is_veri_8e7ab4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["is_active"], name="users_banka_is_acti_9bd641_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bankaccount",
            unique_together={("user", "account_number", "bank_code")},
        ),
    ]
