# Generated by Django 4.2.23 on 2025-08-03 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_bankaccount_transaction_fee_transaction_metadata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("government_id", "Government ID"),
                            ("driver_license", "Driver License"),
                            ("passport", "Passport"),
                            ("cac_document", "CAC Document"),
                            ("vehicle_registration", "Vehicle Registration"),
                            ("insurance_document", "Insurance Document"),
                            ("vehicle_photo", "Vehicle Photo"),
                            ("profile_picture", "Profile Picture"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("secure_filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.PositiveIntegerField()),
                ("file_hash", models.CharField(max_length=64)),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_encrypted", models.BooleanField(default=True)),
                ("access_count", models.PositiveIntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("extracted_info", models.JSONField(blank=True, default=dict)),
                ("verification_notes", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secure_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "secure document",
                "verbose_name_plural": "secure documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="FileSecurityAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("access", "Access"),
                            ("upload", "Upload"),
                            ("download", "Download"),
                            ("delete", "Delete"),
                            ("modify", "Modify"),
                            ("security_check", "Security Check"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_hash", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "file security audit",
                "verbose_name_plural": "file security audits",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("verify", "Verify"),
                            ("reject", "Reject"),
                            ("access", "Access"),
                            ("delete", "Delete"),
                            ("update", "Update"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_logs",
                        to="users.securedocument",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "document verification log",
                "verbose_name_plural": "document verification logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="securedocument",
            index=models.Index(fields=["user"], name="users_secur_user_id_bca832_idx"),
        ),
        migrations.AddIndex(
            model_name="securedocument",
            index=models.Index(
                fields=["document_type"], name="users_secur_documen_bc4723_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securedocument",
            index=models.Index(
                fields=["verification_status"], name="users_secur_verific_8a8018_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securedocument",
            index=models.Index(
                fields=["uploaded_at"], name="users_secur_uploade_e381c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securedocument",
            index=models.Index(
                fields=["file_hash"], name="users_secur_file_ha_ab6e0d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="securedocument",
            unique_together={("user", "document_type", "file_hash")},
        ),
        migrations.AddIndex(
            model_name="filesecurityaudit",
            index=models.Index(fields=["user"], name="users_files_user_id_a101dd_idx"),
        ),
        migrations.AddIndex(
            model_name="filesecurityaudit",
            index=models.Index(
                fields=["audit_type"], name="users_files_audit_t_9fa4fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filesecurityaudit",
            index=models.Index(
                fields=["file_path"], name="users_files_file_pa_f498ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filesecurityaudit",
            index=models.Index(
                fields=["timestamp"], name="users_files_timesta_a6dc1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filesecurityaudit",
            index=models.Index(
                fields=["success"], name="users_files_success_ff8843_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentverificationlog",
            index=models.Index(
                fields=["document"], name="users_docum_documen_2d3d37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentverificationlog",
            index=models.Index(fields=["action"], name="users_docum_action_6794e2_idx"),
        ),
        migrations.AddIndex(
            model_name="documentverificationlog",
            index=models.Index(
                fields=["performed_by"], name="users_docum_perform_46ea9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentverificationlog",
            index=models.Index(
                fields=["timestamp"], name="users_docum_timesta_ceb015_idx"
            ),
        ),
    ]
