# Generated by Django 4.2.23 on 2025-08-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_securedocument_filesecurityaudit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="car_make",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="car_model",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="car_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="license_plate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
