# Generated by Django 4.2.23 on 2025-08-30 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_add_car_fields_to_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_notifications",
        ),
        migrations.RemoveField(
            model_name="user",
            name="in_app_notifications",
        ),
        migrations.RemoveField(
            model_name="user",
            name="notification_frequency",
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="license_back_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="driver/licenses/back/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="license_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="license_front_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="driver/licenses/front/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="license_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="plate_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_photo_back",
            field=models.ImageField(
                blank=True, null=True, upload_to="driver/vehicle_photos/back/"
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_photo_front",
            field=models.ImageField(
                blank=True, null=True, upload_to="driver/vehicle_photos/front/"
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_photo_left",
            field=models.ImageField(
                blank=True, null=True, upload_to="driver/vehicle_photos/left/"
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_photo_right",
            field=models.ImageField(
                blank=True, null=True, upload_to="driver/vehicle_photos/right/"
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="cac_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="mechanic/cac_documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="cac_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="lga",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="selfie",
            field=models.ImageField(
                blank=True,
                help_text="Live photo of mechanic",
                null=True,
                upload_to="mechanic/selfies/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="cac_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="merchant/cac_documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="lga",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="selfie",
            field=models.ImageField(
                blank=True,
                help_text="Live photo of merchant",
                null=True,
                upload_to="merchant/selfies/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("primary_user", "Primary User"),
                    ("driver", "Driver"),
                    ("rider", "Rider"),
                    ("mechanic", "Mechanic"),
                    ("merchant", "Merchant"),
                    ("developer", "Developer"),
                ],
                max_length=50,
                unique=True,
                verbose_name="role name",
            ),
        ),
    ]
