# Generated by Django 4.2.23 on 2025-09-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_remove_user_email_notifications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                # Removed unique=True to allow same email for different roles
            ),
        ),
    ]


