# Generated by Django 4.2.23 on 2025-09-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_remove_email_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanicprofile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
