# Generated by Django 4.2.23 on 2025-10-24 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_mechanicprofile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mechanicprofile",
            name="government_id",
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="drivers_license_back",
            field=models.FileField(
                blank=True,
                help_text="Back of Driver's License",
                null=True,
                upload_to="mechanic/ids/drivers_license/back/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="drivers_license_front",
            field=models.FileField(
                blank=True,
                help_text="Front of Driver's License",
                null=True,
                upload_to="mechanic/ids/drivers_license/front/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="international_passport",
            field=models.FileField(
                blank=True,
                help_text="International Passport Bio Page",
                null=True,
                upload_to="mechanic/ids/international_passport/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="national_id_back",
            field=models.FileField(
                blank=True,
                help_text="Back of National Identity Card",
                null=True,
                upload_to="mechanic/ids/national_id/back/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="national_id_front",
            field=models.FileField(
                blank=True,
                help_text="Front of National Identity Card",
                null=True,
                upload_to="mechanic/ids/national_id/front/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="pvc_back",
            field=models.FileField(
                blank=True,
                help_text="Back of Permanent Voter's Card (PVC)",
                null=True,
                upload_to="mechanic/ids/pvc/back/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="pvc_front",
            field=models.FileField(
                blank=True,
                help_text="Front of Permanent Voter's Card (PVC)",
                null=True,
                upload_to="mechanic/ids/pvc/front/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="voters_card_back",
            field=models.FileField(
                blank=True,
                help_text="Back of Voter's Card",
                null=True,
                upload_to="mechanic/ids/voters_card/back/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="voters_card_front",
            field=models.FileField(
                blank=True,
                help_text="Front of Voter's Card",
                null=True,
                upload_to="mechanic/ids/voters_card/front/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
    ]
