# Generated by Django 4.2.23 on 2025-10-24 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_remove_mechanicprofile_government_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mechanicprofile",
            name="drivers_license_back",
        ),
        migrations.RemoveField(
            model_name="mechanicprofile",
            name="drivers_license_front",
        ),
        migrations.RemoveField(
            model_name="mechanicprofile",
            name="international_passport",
        ),
        migrations.RemoveField(
            model_name="mechanicprofile",
            name="national_id_back",
        ),
        migrations.RemoveField(
            model_name="mechanicprofile",
            name="national_id_front",
        ),
        migrations.RemoveField(
            model_name="mechanicprofile",
            name="pvc_back",
        ),
        migrations.RemoveField(
            model_name="mechanicprofile",
            name="pvc_front",
        ),
        migrations.RemoveField(
            model_name="mechanicprofile",
            name="voters_card_back",
        ),
        migrations.RemoveField(
            model_name="mechanicprofile",
            name="voters_card_front",
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="government_id_back",
            field=models.FileField(
                blank=True,
                help_text="Back of Government Identity Card",
                null=True,
                upload_to="mechanic/ids/government_id/back/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="government_id_front",
            field=models.FileField(
                blank=True,
                help_text="Front of Government Identity Card",
                null=True,
                upload_to="mechanic/ids/government_id/front/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="govt_id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NIN", "NIN"),
                    ("drivers_license", "Drivers license"),
                    ("voters_card", "Voters card"),
                    ("international_passport", "International passport"),
                    ("permanent_voters_card", "Permanent voter’s card"),
                ],
                help_text="Type of government ID provided",
                max_length=32,
                null=True,
            ),
        ),
    ]
