# Generated by Django 4.2.23 on 2025-11-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_remove_mechanicprofile_drivers_license_back_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanicprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Mechanic's location latitude for proximity-based requests",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Mechanic's location longitude for proximity-based requests",
                max_digits=9,
                null=True,
            ),
        ),
    ]
