# Generated by Django 4.2.23 on 2025-11-30 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_mechanicprofile_latitude_mechanicprofile_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="Role for which this notification is intended",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="users.role",
            ),
        ),
    ]
