# Generated by Django 4.2.23 on 2025-12-21 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_add_role_to_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useractivitylog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "User Activity Log",
                "verbose_name_plural": "User Activity Logs",
            },
        ),
        migrations.RemoveIndex(
            model_name="useractivitylog",
            name="users_usera_severit_8ed6ec_idx",
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="category",
            field=models.CharField(
                choices=[
                    ("authentication", "Authentication"),
                    ("authorization", "Authorization"),
                    ("transaction", "Transaction"),
                    ("data_modification", "Data Modification"),
                    ("security", "Security"),
                    ("compliance", "Compliance"),
                    ("business_critical", "Business Critical"),
                ],
                db_index=True,
                default="business_critical",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="request_method",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="request_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="response_status",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="response_time_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="session_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="success",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="action",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="object_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                db_index=True,
                default="low",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["severity", "category"], name="users_usera_severit_766287_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["timestamp", "category"], name="users_usera_timesta_5c101a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["user", "category", "timestamp"],
                name="users_usera_user_id_7dd5b5_idx",
            ),
        ),
    ]
