# Generated by Django 4.2.23 on 2025-12-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_alter_useractivitylog_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("primary_user", "Primary User"),
                    ("driver", "Driver"),
                    ("rider", "Rider"),
                    ("mechanic", "Mechanic"),
                    ("merchant", "Merchant"),
                    ("developer", "Developer"),
                    ("admin", "Admin"),
                ],
                max_length=50,
                unique=True,
                verbose_name="role name",
            ),
        ),
    ]
