# Generated by Django 4.2.23 on 2025-12-30 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_user_profile_fields"),
        ("users", "0020_alter_role_name"),
    ]

    operations = []
