# Generated by Django 4.2.23 on 2026-02-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_merge_20251230_2347"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="last name"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("unsubscribed", "Unsubscribed"),
                            ("bounced", "Bounced"),
                            ("complained", "Complained"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="subscribed at"
                    ),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="unsubscribed at"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="website",
                        max_length=100,
                        verbose_name="subscription source",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
            ],
            options={
                "verbose_name": "email subscription",
                "verbose_name_plural": "email subscriptions",
                "ordering": ["-subscribed_at"],
                "indexes": [
                    models.Index(fields=["email"], name="users_email_email_912e03_idx"),
                    models.Index(
                        fields=["status"], name="users_email_status_bcd225_idx"
                    ),
                    models.Index(
                        fields=["subscribed_at"], name="users_email_subscri_ea863b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                (
                    "contact_number",
                    models.CharField(max_length=20, verbose_name="contact number"),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="company name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="is read")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="responded at"
                    ),
                ),
                (
                    "response_notes",
                    models.TextField(blank=True, verbose_name="response notes"),
                ),
            ],
            options={
                "verbose_name": "contact message",
                "verbose_name_plural": "contact messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="users_conta_email_94d804_idx"),
                    models.Index(
                        fields=["status"], name="users_conta_status_5ce107_idx"
                    ),
                    models.Index(
                        fields=["is_read"], name="users_conta_is_read_4631fa_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="users_conta_created_ee8a5f_idx"
                    ),
                ],
            },
        ),
    ]
