# Generated by Django 4.2.23 on 2026-02-22 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_emailsubscription_contactmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchantprofile",
            name="profile_picture",
        ),
    ]
