# Generated by Django 4.2.23 on 2026-02-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_remove_merchant_profile_picture"),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentVerificationLog',
        ),
        migrations.DeleteModel(
            name='FileSecurityAudit',
        ),
        migrations.DeleteModel(
            name='SecureDocument',
        ),
    ]
