# Generated by Django 4.2.23 on 2026-02-22 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_delete_obsolete_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="selfie",
            field=models.ImageField(
                blank=True,
                help_text="Live photo of driver",
                null=True,
                upload_to="driver/selfies/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
