# Generated by Django 4.2.23 on 2026-02-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_driverprofile_selfie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mechanicprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Mechanic's location latitude for proximity-based requests",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mechanicprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Mechanic's location longitude for proximity-based requests",
                max_digits=20,
                null=True,
            ),
        ),
    ]
