# Generated by Django 4.2.23 on 2026-02-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_alter_driverprofile_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=17, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=17, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mechanicprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=17,
                help_text="Mechanic's location latitude for proximity-based requests",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mechanicprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=17,
                help_text="Mechanic's location longitude for proximity-based requests",
                max_digits=20,
                null=True,
            ),
        ),
    ]
