# Generated by Django 4.2.23 on 2026-02-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_alter_driverprofile_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driverprofile",
            name="vehicle_plate",
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="license_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="vehicle_color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="vehicle_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
