# Generated by Django 4.2.23 on 2026-02-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_remove_driverprofile_vehicle_plate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="disapproval_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="disapproved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="disapproval_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="disapproved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="disapproval_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="disapproved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
