# Generated by Django 4.2.23 on 2026-03-01 12:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_driverprofile_disapproval_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "selfie",
                    models.ImageField(
                        blank=True,
                        help_text="Live photo of rider",
                        null=True,
                        upload_to="rider/selfies/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "government_id",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="rider/ids/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("disapproved", models.BooleanField(default=False)),
                ("disapproval_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "rider profile",
                "verbose_name_plural": "rider profiles",
                "indexes": [
                    models.Index(
                        fields=["user"], name="users_rider_user_id_884f3a_idx"
                    ),
                    models.Index(
                        fields=["is_approved"], name="users_rider_is_appr_bb15d8_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="users_rider_created_60578a_idx"
                    ),
                ],
            },
        ),
    ]
