# Generated by Django 4.2.23 on 2026-03-02 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_riderprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driverprofile",
            name="government_id",
        ),
        migrations.RemoveField(
            model_name="riderprofile",
            name="government_id",
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="government_id_back",
            field=models.FileField(
                blank=True,
                help_text="Back of Government Identity Card",
                null=True,
                upload_to="driver/ids/government_id/back/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="government_id_front",
            field=models.FileField(
                blank=True,
                help_text="Front of Government Identity Card",
                null=True,
                upload_to="driver/ids/government_id/front/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="govt_id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NIN", "NIN"),
                    ("drivers_license", "Drivers license"),
                    ("voters_card", "Voters card"),
                    ("international_passport", "International passport"),
                    ("permanent_voters_card", "Permanent voter’s card"),
                ],
                help_text="Type of government ID provided",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="government_id_back",
            field=models.FileField(
                blank=True,
                help_text="Back of Government Identity Card",
                null=True,
                upload_to="rider/ids/government_id/back/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="government_id_front",
            field=models.FileField(
                blank=True,
                help_text="Front of Government Identity Card",
                null=True,
                upload_to="rider/ids/government_id/front/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="govt_id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NIN", "NIN"),
                    ("drivers_license", "Drivers license"),
                    ("voters_card", "Voters card"),
                    ("international_passport", "International passport"),
                    ("permanent_voters_card", "Permanent voter’s card"),
                ],
                help_text="Type of government ID provided",
                max_length=32,
                null=True,
            ),
        ),
    ]
