# Generated by Django 4.2.23 on 2026-03-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_remove_driverprofile_government_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
