# Generated by Cascade on 2026-03-07

from django.db import migrations, models


def backfill_bank_accounts_from_profiles(apps, schema_editor):
    BankAccount = apps.get_model("users", "BankAccount")
    DriverProfile = apps.get_model("users", "DriverProfile")

    db_alias = schema_editor.connection.alias

    # Backfill from DriverProfile only (it's the only profile with legacy bank
    # fields currently).
    profiles = (
        DriverProfile.objects.using(db_alias)
        .exclude(account_number__isnull=True)
        .exclude(account_number="")
    )

    for profile in profiles.iterator():
        user_id = profile.user_id
        account_number = (profile.account_number or "").strip()
        bank_name = (profile.bank_name or "").strip()

        if not account_number:
            continue

        existing_for_user = BankAccount.objects.using(db_alias).filter(
            user_id=user_id
        )

        # If there's already a matching account_number for the user, skip
        if existing_for_user.filter(account_number=account_number).exists():
            continue

        # If user already has a default, keep it; otherwise set this first
        # backfilled one as default.
        has_default = existing_for_user.filter(is_default=True).exists()

        BankAccount.objects.using(db_alias).create(
            user_id=user_id,
            account_number=account_number,
            account_name="",
            bank_code="",
            bank_name=bank_name or "",
            is_verified=False,
            is_active=True,
            is_default=not has_default,
        )


def ensure_single_default_per_user(apps, schema_editor):
    BankAccount = apps.get_model("users", "BankAccount")

    db_alias = schema_editor.connection.alias

    user_ids = (
        BankAccount.objects.using(db_alias)
        .filter(is_default=True)
        .values_list("user_id", flat=True)
        .distinct()
    )

    for user_id in user_ids.iterator():
        defaults = (
            BankAccount.objects.using(db_alias)
            .filter(user_id=user_id, is_default=True)
            .order_by("-is_verified", "-created_at", "-id")
        )
        keep = defaults.first()
        if keep is None:
            continue
        (
            BankAccount.objects.using(db_alias)
            .filter(user_id=user_id, is_default=True)
            .exclude(id=keep.id)
            .update(is_default=False)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_driverprofile_state_riderprofile_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            backfill_bank_accounts_from_profiles, migrations.RunPython.noop
        ),
        migrations.RunPython(
            ensure_single_default_per_user, migrations.RunPython.noop
        ),
    ]
