# Generated by Cascade on 2026-03-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_bankaccount_is_default_and_backfill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driverprofile",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="driverprofile",
            name="account_number",
        ),
    ]
