# Generated by Cascade on 2026-03-07

from django.db import migrations, models


def copy_business_address_to_state(apps, schema_editor):
    MerchantProfile = apps.get_model("users", "MerchantProfile")

    db_alias = schema_editor.connection.alias

    qs = MerchantProfile.objects.using(db_alias).exclude(state__isnull=False)
    for mp in qs.iterator():
        business_address = getattr(mp, "business_address", None)
        if business_address:
            mp.state = business_address
            mp.save(update_fields=["state"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_remove_driverprofile_bank_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanicprofile",
            name="area_of_specialisation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(
            copy_business_address_to_state,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="merchantprofile",
            name="business_address",
        ),
    ]
