# Generated by Cascade on 2026-03-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_mechanic_experience_and_merchant_state"),
    ]

    operations = []
