# Generated by Cascade on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_remove_mechanicprofile_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantprofile",
            name="store_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
