# Generated by Django 4.2.23 on 2026-03-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0037_merchantprofile_store_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=17, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=17, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=17,
                help_text="Mechanic's location latitude for proximity-based requests",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=17,
                help_text="Mechanic's location longitude for proximity-based requests",
                max_digits=20,
                null=True,
            ),
        ),
    ]
