# Generated by Django 4.2.23 on 2026-03-11 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0038_merchantprofile_latitude_merchantprofile_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="license_back_image",
            field=models.ImageField(
                blank=True,
                help_text="Back of the license",
                null=True,
                upload_to="rider/licenses/back/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="license_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="license_front_image",
            field=models.ImageField(
                blank=True,
                help_text="Front of the license",
                null=True,
                upload_to="rider/licenses/front/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="license_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="license_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="plate_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="ride_photo_back",
            field=models.ImageField(
                blank=True,
                help_text="Back photo of the ride",
                null=True,
                upload_to="rider/ride_photos/back/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="ride_photo_front",
            field=models.ImageField(
                blank=True,
                help_text="Front photo of the ride",
                null=True,
                upload_to="rider/ride_photos/front/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="ride_registration_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="ride_type",
            field=models.CharField(
                blank=True,
                choices=[("bicycle", "Bicycle"), ("motorcycle", "Motorcycle")],
                max_length=20,
                null=True,
            ),
        ),
    ]
