# Generated by Django 4.2.23 on 2026-03-20 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0039_riderprofile_date_of_birth_riderprofile_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantprofile",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="subscription_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="subscription_payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                    ("refund", "Refund"),
                    ("withdrawal", "Withdrawal"),
                    ("deposit", "Deposit"),
                    ("payment", "Payment"),
                    ("top_up", "Top Up"),
                    ("transfer", "Transfer"),
                    ("fee", "Fee"),
                    ("subscription", "Subscription"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="users.wallet",
            ),
        ),
    ]
