# Generated by Django 4.2.23 on 2026-04-12 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_merchantprofile_is_subscribed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number (VIN)', max_length=17, null=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(limit_choices_to={'roles__name': 'primary_user'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user vehicle',
                'verbose_name_plural': 'user vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='users/vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.uservehicle')),
            ],
            options={
                'verbose_name': 'user vehicle image',
                'verbose_name_plural': 'user vehicle images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uservehicle',
            index=models.Index(fields=['user'], name='users_userv_user_id_ead84b_idx'),
        ),
        migrations.AddIndex(
            model_name='uservehicle',
            index=models.Index(fields=['vin'], name='users_userv_vin_213ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='uservehicle',
            index=models.Index(fields=['license_plate'], name='users_userv_license_4500bd_idx'),
        ),
    ]
