# Generated by Django 4.2.23 on 2026-04-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_uservehicle_uservehicleimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='car_make',
        ),
        migrations.RemoveField(
            model_name='user',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='user',
            name='car_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_plate',
        ),
    ]
