# Generated by Django 4.2.23 on 2026-04-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_remove_user_car_make_remove_user_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.UUIDField(blank=True, help_text='UUID of the object this notification is related to', null=True, verbose_name='related object id'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, help_text='Type of the object this notification is related to (e.g., RepairRequest)', max_length=50, null=True, verbose_name='related object type'),
        ),
    ]
