# Generated by Django 4.2.23 on 2026-05-01 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_notification_related_object_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanicprofile',
            old_name='area_of_specialisation',
            new_name='areas_of_specialisation',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='nin_document',
            field=models.FileField(blank=True, null=True, upload_to='driver/nin_documents/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='nin_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='areas_of_specialisation',
            field=models.JSONField(blank=True, default=list, help_text='Multiple areas of specialization', null=True),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='nin_document',
            field=models.FileField(blank=True, null=True, upload_to='mechanic/nin_documents/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='nin_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='nin_document',
            field=models.FileField(blank=True, null=True, upload_to='merchant/nin_documents/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='nin_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='nin_document',
            field=models.FileField(blank=True, null=True, upload_to='rider/nin_documents/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='nin_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
