# Generated by Django 4.2.23 on 2026-05-02 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_remove_mechanicprofile_area_of_specialisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='certificate_of_learning',
            field=models.FileField(blank=True, null=True, upload_to='mechanic/certificates/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
