# Generated by Django 4.2.23 on 2026-05-04 19:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0045_mechanicprofile_certificate_of_learning"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaOfSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "area of specialization",
                "verbose_name_plural": "areas of specialization",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="mechanicprofile",
            name="areas_of_specialisation",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Multiple areas of specialization (legacy)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("primary_user", "Primary User"),
                    ("driver", "Driver"),
                    ("rider", "Rider"),
                    ("mechanic", "Mechanic"),
                    ("merchant", "Merchant"),
                    ("developer", "Developer"),
                    ("admin", "Admin"),
                    ("vehicle_rental", "Vehicle Rental"),
                ],
                max_length=50,
                unique=True,
                verbose_name="role name",
            ),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="specializations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Standardized areas of specialization",
                related_name="mechanics",
                to="users.areaofspecialization",
            ),
        ),
        migrations.CreateModel(
            name="VehicleRentalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=17, max_digits=20, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=17, max_digits=20, null=True
                    ),
                ),
                ("lga", models.CharField(blank=True, max_length=100, null=True)),
                ("cac_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cac_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="vehicle_rental/cac_documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "selfie",
                    models.ImageField(
                        blank=True,
                        help_text="Live photo of the rental operator",
                        null=True,
                        upload_to="vehicle_rental/selfies/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("nin_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "nin_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="vehicle_rental/nin_documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_rental_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle rental profile",
                "verbose_name_plural": "vehicle rental profiles",
                "indexes": [
                    models.Index(
                        fields=["user"], name="users_vehic_user_id_5ad972_idx"
                    ),
                    models.Index(
                        fields=["company_name"], name="users_vehic_company_878479_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="users_vehic_created_3898ff_idx"
                    ),
                ],
            },
        ),
    ]
