# Generated by Django 4.2.23 on 2026-05-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0047_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("info", "Information"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                    ("success", "Success"),
                    ("support_chat", "Admin Support Chat"),
                    ("chat", "User-to-User Chat"),
                    ("order_status", "Order Status Update"),
                    ("ride_status", "Ride Status Update"),
                    ("repair_status", "Repair Status Update"),
                    ("repair_update", "Repair Update"),
                    ("rental_status", "Rental Status Update"),
                ],
                default="info",
                max_length=20,
                verbose_name="notification type",
            ),
        ),
    ]
