# Generated by Django 4.2.23 on 2026-05-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0048_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanicprofile",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="subscription_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="subscription_payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehiclerentalprofile",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehiclerentalprofile",
            name="subscription_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehiclerentalprofile",
            name="subscription_payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
