# Generated by Django 4.2.23 on 2026-06-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerentalprofile',
            name='disapproval_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerentalprofile',
            name='disapproved',
            field=models.BooleanField(default=False),
        ),
    ]
