# Generated by Django 4.2.23 on 2026-09-27 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0051_vehiclerentalprofile_disapproval_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="nin_is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="nin_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="nin_is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mechanicprofile",
            name="nin_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="nin_is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="nin_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="nin_is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="nin_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehiclerentalprofile",
            name="nin_is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehiclerentalprofile",
            name="nin_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="NINVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nin_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("partial_match", "Partial Match"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Role context (mechanic, merchant, driver, rider, vehicle_rental)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("response_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nin_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NIN verification",
                "verbose_name_plural": "NIN verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="users_ninve_user_id_f65f01_idx"
                    ),
                    models.Index(
                        fields=["nin_number"], name="users_ninve_nin_num_0d5ffa_idx"
                    ),
                    models.Index(
                        fields=["request_id"], name="users_ninve_request_e03537_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="users_ninve_created_f063d4_idx"
                    ),
                ],
            },
        ),
    ]
