# Generated by Django 4.2.23 on 2026-10-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_setup_google_social_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='nin_document',
        ),
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='nin_document',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='nin_document',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='nin_document',
        ),
        migrations.RemoveField(
            model_name='vehiclerentalprofile',
            name='nin_document',
        ),
    ]
