# Generated by Django 4.2.23 on 2025-11-30 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("merchant", "Merchant"),
                            ("driver", "Driver"),
                            ("mechanic", "Mechanic"),
                            ("customer", "Customer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analytics_analyticsdashboard",
                "ordering": ["role", "title"],
                "unique_together": {("role", "title")},
            },
        ),
        migrations.CreateModel(
            name="AnalyticsCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=200, unique=True)),
                ("data", models.JSONField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analytics_analyticscache",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["key"], name="analytics_a_key_ade760_idx"),
                    models.Index(
                        fields=["expires_at"], name="analytics_a_expires_4e35a3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_type", models.CharField(max_length=50)),
                ("data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_useranalytics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="analytics_u_user_id_a24cf9_idx"
                    ),
                    models.Index(
                        fields=["data_type"], name="analytics_u_data_ty_4ac943_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="analytics_u_timesta_e8c5cf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("metric", "Metric Card"),
                            ("chart", "Chart"),
                            ("table", "Data Table"),
                            ("list", "List"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("line", "Line Chart"),
                            ("bar", "Bar Chart"),
                            ("pie", "Pie Chart"),
                            ("doughnut", "Doughnut Chart"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("data_source", models.CharField(max_length=100)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="adminpanel.analyticsdashboard",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_analyticswidget",
                "ordering": ["dashboard", "position"],
                "unique_together": {("dashboard", "title")},
            },
        ),
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales Report"),
                            ("rides", "Rides Report"),
                            ("couriers", "Couriers Report"),
                            ("mechanics", "Mechanics Report"),
                            ("rentals", "Rentals Report"),
                            ("users", "Users Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("data", models.JSONField()),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_analyticsreport",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type"], name="analytics_a_report__07a16b_idx"
                    ),
                    models.Index(
                        fields=["generated_by"], name="analytics_a_generat_06df96_idx"
                    ),
                    models.Index(
                        fields=["date_from", "date_to"],
                        name="analytics_a_date_fr_09434a_idx",
                    ),
                ],
            },
        ),
    ]
