# Generated by Django 4.2.23 on 2025-08-03 02:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.TimeField(default="09:00:00")),
                ("end_time", models.TimeField(default="17:00:00")),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("booking_reference", models.CharField(max_length=20, unique=True)),
                ("pickup_location", models.TextField()),
                ("return_location", models.TextField()),
                (
                    "pickup_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "return_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "return_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("special_requests", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"roles__name": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        limit_choices_to={"is_rental": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_bookings",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-booked_at"],
            },
        ),
        migrations.CreateModel(
            name="RentalReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rental",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="rentals.rentalbooking",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["rental"], name="rentals_ren_rental__9066db_idx"
                    ),
                    models.Index(
                        fields=["customer"], name="rentals_ren_custome_ac67af_idx"
                    ),
                    models.Index(
                        fields=["rating"], name="rentals_ren_rating_6c4830_idx"
                    ),
                ],
                "unique_together": {("rental", "customer")},
            },
        ),
        migrations.CreateModel(
            name="RentalPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_available", models.BooleanField(default=True)),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_periods",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
                "indexes": [
                    models.Index(
                        fields=["product"], name="rentals_ren_product_0925ef_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="rentals_ren_start_d_aa1043_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="rentals_ren_end_dat_c299dd_idx"
                    ),
                    models.Index(
                        fields=["is_available"], name="rentals_ren_is_avai_28d72d_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="rentalbooking",
            index=models.Index(
                fields=["customer"], name="rentals_ren_custome_2ad8f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalbooking",
            index=models.Index(
                fields=["product"], name="rentals_ren_product_6f85f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalbooking",
            index=models.Index(fields=["status"], name="rentals_ren_status_8ec735_idx"),
        ),
        migrations.AddIndex(
            model_name="rentalbooking",
            index=models.Index(
                fields=["start_date"], name="rentals_ren_start_d_adba9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalbooking",
            index=models.Index(
                fields=["end_date"], name="rentals_ren_end_dat_74dd75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalbooking",
            index=models.Index(
                fields=["booking_reference"], name="rentals_ren_booking_496e81_idx"
            ),
        ),
    ]
