# Generated by Django 4.2.23 on 2025-07-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ride",
            old_name="dropoff_location",
            new_name="dropoff_address",
        ),
        migrations.RenameField(
            model_name="ride",
            old_name="pickup_location",
            new_name="pickup_address",
        ),
        migrations.AddField(
            model_name="ride",
            name="dropoff_latitude",
            field=models.DecimalField(decimal_places=6, default=12, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ride",
            name="dropoff_longitude",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ride",
            name="pickup_latitude",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ride",
            name="pickup_longitude",
            field=models.DecimalField(decimal_places=6, default=12, max_digits=9),
            preserve_default=False,
        ),
    ]
