# Generated by Django 4.2.23 on 2025-07-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0003_courierrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="distance_km",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="duration_min",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
