# Generated by Django 4.2.23 on 2025-07-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0004_ride_distance_km_ride_duration_min"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("requested", "Requested"),
                    ("accepted", "Accepted"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                max_length=32,
            ),
        ),
    ]
