# Generated by Django 4.2.23 on 2025-07-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0005_alter_ride_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("requested", "Requested"),
                    ("accepted", "Accepted"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="initiated",
                max_length=32,
            ),
        ),
    ]
