# Generated by Django 4.2.23 on 2025-07-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0006_alter_ride_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="distance_km",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="duration_min",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
