# Generated by Django 4.2.23 on 2025-08-03 22:20

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0007_alter_ride_distance_km_alter_ride_duration_min"),
    ]

    operations = [
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "waypoint_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("dropoff", "Dropoff"),
                            ("waypoint", "Waypoint"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sequence_order",
                    models.PositiveIntegerField(
                        help_text="Order of waypoint in the route (1 = first, 2 = second, etc.)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=100)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("instructions", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sequence_order"],
            },
        ),
        migrations.AddField(
            model_name="courierrequest",
            name="current_waypoint_index",
            field=models.PositiveIntegerField(
                default=0, help_text="Current waypoint being processed"
            ),
        ),
        migrations.AddField(
            model_name="courierrequest",
            name="route_polyline",
            field=models.TextField(
                blank=True, help_text="Encoded polyline for route visualization"
            ),
        ),
        migrations.AddField(
            model_name="courierrequest",
            name="total_distance_km",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="courierrequest",
            name="total_duration_min",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="current_waypoint_index",
            field=models.PositiveIntegerField(
                default=0, help_text="Current waypoint being processed"
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="route_polyline",
            field=models.TextField(
                blank=True, help_text="Encoded polyline for route visualization"
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="total_distance_km",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="total_duration_min",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="courierrequest",
            name="dropoff_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="courierrequest",
            name="dropoff_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="courierrequest",
            name="dropoff_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="courierrequest",
            name="pickup_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="courierrequest",
            name="pickup_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="courierrequest",
            name="pickup_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="dropoff_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="ride",
            name="dropoff_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="dropoff_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="courierrequest",
            index=models.Index(
                fields=["current_waypoint_index"], name="rides_couri_current_4297cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["current_waypoint_index"], name="rides_ride_current_50fa2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waypoint",
            index=models.Index(
                fields=["waypoint_type"], name="rides_waypo_waypoin_c36e95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waypoint",
            index=models.Index(
                fields=["sequence_order"], name="rides_waypo_sequenc_093dcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waypoint",
            index=models.Index(
                fields=["is_completed"], name="rides_waypo_is_comp_7126f7_idx"
            ),
        ),
        migrations.AddField(
            model_name="courierrequest",
            name="waypoints",
            field=models.ManyToManyField(
                related_name="courier_requests", to="rides.waypoint"
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="waypoints",
            field=models.ManyToManyField(related_name="rides", to="rides.waypoint"),
        ),
    ]
