# Generated by Django 4.2.23 on 2026-02-12 10:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rides", "0008_waypoint_courierrequest_current_waypoint_index_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RideRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "driving_skill_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "punctuality_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "vehicle_condition_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "communication_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("rated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_ratings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "ordering": ["-rated_at"],
                "indexes": [
                    models.Index(
                        fields=["ride"], name="rides_rider_ride_id_233b46_idx"
                    ),
                    models.Index(
                        fields=["customer"], name="rides_rider_custome_756454_idx"
                    ),
                    models.Index(
                        fields=["driver"], name="rides_rider_driver__8a9a1e_idx"
                    ),
                    models.Index(
                        fields=["overall_rating"], name="rides_rider_overall_3cac69_idx"
                    ),
                    models.Index(
                        fields=["rated_at"], name="rides_rider_rated_a_1779f8_idx"
                    ),
                ],
            },
        ),
    ]
