# Generated by Django 4.2.23 on 2026-03-08 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0009_riderating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourierRequest",
        ),
    ]
