# Generated by Django 4.2.23 on 2025-10-05 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mechanics", "0003_remove_repairrequest_symptoms"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclemake",
            name="parent_make",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is a car model, select its make. Leave blank for makes.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="mechanics.vehiclemake",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemake",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="vehiclemake",
            unique_together={("name", "parent_make")},
        ),
        migrations.AddIndex(
            model_name="vehiclemake",
            index=models.Index(
                fields=["parent_make"], name="mechanics_v_parent__28634e_idx"
            ),
        ),
    ]
