# Generated by Django 4.2.23 on 2026-04-02 21:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0024_remove_repairbiddinglisting_mechanics_r_merchan_d348b2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('labor_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('complexity_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('urgency_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parts_markup', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PricingRule',
        ),

        migrations.AlterModelOptions(
            name='serviceprice',
            options={'ordering': ['service_type__name', 'vehicle_make__name', 'vehicle_model__name']},
        ),
        migrations.AlterUniqueTogether(
            name='serviceprice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='default_labor_hours',
        ),
        migrations.AddField(
            model_name='repairrequest',
            name='service_category',
            field=models.ForeignKey(blank=True, help_text='Standardized service category for pricing rules', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_requests', to='mechanics.servicetype'),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, help_text='Leave blank if it applies to all models of the make.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_prices_by_model', to='mechanics.vehiclemake'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='vehicle_make',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this is a generic base price.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_prices_by_make', to='mechanics.vehiclemake'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(help_text='e.g., Tire Replacement, Engine Diagnostics', max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='serviceprice',
            unique_together={('service_type', 'vehicle_make', 'vehicle_model')},
        ),
        migrations.DeleteModel(
            name='RepairBid',
        ),
        migrations.DeleteModel(
            name='RepairBiddingListing',
        ),
        migrations.AddField(
            model_name='settlement',
            name='repair_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='mechanics.repairrequest'),
        ),
        migrations.RemoveField(
            model_name='serviceprice',
            name='price',
        ),
    ]
