# Generated by Django 4.2.23 on 2026-04-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0025_settlement_delete_pricingrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='ServicePrice',
        ),
    ]
