# Generated by Django 4.2.23 on 2026-04-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0026_servicetype_base_price_delete_serviceprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['name', 'vehicle_make__name', 'vehicle_model__name']},
        ),
        migrations.AddField(
            model_name='servicetype',
            name='vehicle_make',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this is a generic service type.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_types_by_make', to='mechanics.vehiclemake'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, help_text='Leave blank if it applies to all models of the make.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_types_by_model', to='mechanics.vehiclemake'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(help_text='e.g., Tire Replacement, Engine Diagnostics', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='servicetype',
            unique_together={('name', 'vehicle_make', 'vehicle_model')},
        ),
    ]
