# Generated by Django 4.2.23 on 2025-07-31 04:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pickup_address", models.TextField()),
                (
                    "pickup_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("pickup_contact_name", models.CharField(max_length=100)),
                ("pickup_contact_phone", models.CharField(max_length=20)),
                ("pickup_instructions", models.TextField(blank=True)),
                ("delivery_address", models.TextField()),
                (
                    "delivery_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "delivery_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("delivery_contact_name", models.CharField(max_length=100)),
                ("delivery_contact_phone", models.CharField(max_length=20)),
                ("delivery_instructions", models.TextField(blank=True)),
                ("package_description", models.TextField()),
                (
                    "package_weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("package_dimensions", models.CharField(blank=True, max_length=50)),
                ("is_fragile", models.BooleanField(default=False)),
                ("requires_signature", models.BooleanField(default=False)),
                (
                    "estimated_distance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("estimated_duration", models.IntegerField(blank=True, null=True)),
                ("base_fare", models.DecimalField(decimal_places=2, max_digits=8)),
                ("distance_fare", models.DecimalField(decimal_places=2, max_digits=8)),
                ("total_fare", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("online", "Online Payment"),
                            ("cash_on_delivery", "Cash on Delivery"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned to Driver"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "driver_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "driver_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("last_location_update", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"roles__name": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"roles__name": "driver"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_delivery_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_updates",
                        to="couriers.deliveryrequest",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_tracking_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CourierRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "delivery_speed_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "service_quality_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "communication_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courier_ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="couriers.deliveryrequest",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courier_ratings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("delivery_request", "customer")},
            },
        ),
    ]
