# Generated by Django 4.2.23 on 2025-08-03 22:20

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("couriers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryrequest",
            name="current_waypoint_index",
            field=models.PositiveIntegerField(
                default=0, help_text="Current waypoint being processed"
            ),
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="route_polyline",
            field=models.TextField(
                blank=True, help_text="Encoded polyline for route visualization"
            ),
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="total_distance_km",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="total_duration_min",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="delivery_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="delivery_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="delivery_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="delivery_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="delivery_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="package_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="package_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="pickup_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="pickup_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="pickup_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="pickup_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="pickup_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.CreateModel(
            name="DeliveryWaypoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address", models.TextField()),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "waypoint_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("dropoff", "Dropoff"),
                            ("waypoint", "Waypoint"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sequence_order",
                    models.PositiveIntegerField(
                        help_text="Order of waypoint in the route (1 = first, 2 = second, etc.)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=100)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("instructions", models.TextField(blank=True)),
                ("package_description", models.TextField(blank=True)),
                (
                    "package_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("package_dimensions", models.CharField(blank=True, max_length=50)),
                ("is_fragile", models.BooleanField(default=False)),
                ("requires_signature", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sequence_order"],
                "indexes": [
                    models.Index(
                        fields=["waypoint_type"], name="couriers_de_waypoin_e378eb_idx"
                    ),
                    models.Index(
                        fields=["sequence_order"], name="couriers_de_sequenc_4af69b_idx"
                    ),
                    models.Index(
                        fields=["is_completed"], name="couriers_de_is_comp_fd8958_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="waypoints",
            field=models.ManyToManyField(
                related_name="delivery_requests", to="couriers.deliverywaypoint"
            ),
        ),
    ]
