# Generated by Django 4.2.23 on 2025-09-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["stock"], name="products_pr_stock_4d23d5_idx"),
        ),
    ]
