# Generated by Django 4.2.23 on 2025-09-07 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_product_stock_product_products_pr_stock_4d23d5_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowMerchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        limit_choices_to={"roles__name": "merchant"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_merchants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="products_fo_user_id_7f0e45_idx"
                    ),
                    models.Index(
                        fields=["merchant"], name="products_fo_merchan_91aa19_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="products_fo_created_5d8959_idx"
                    ),
                ],
                "unique_together": {("user", "merchant")},
            },
        ),
        migrations.CreateModel(
            name="FavoriteProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="products_fa_user_id_436feb_idx"
                    ),
                    models.Index(
                        fields=["product"], name="products_fa_product_4607b8_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="products_fa_created_8f9d9e_idx"
                    ),
                ],
                "unique_together": {("user", "product")},
            },
        ),
    ]
