# Generated by Django 4.2.23 on 2025-10-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_air_conditioning_product_alloy_wheels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="abs",
            field=models.BooleanField(
                default=False, help_text="Anti-lock Braking System (ABS)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="airbags",
            field=models.BooleanField(default=False, help_text="Airbags"),
        ),
        migrations.AddField(
            model_name="product",
            name="blind_spot_monitor",
            field=models.BooleanField(default=False, help_text="Blind Spot Monitor"),
        ),
        migrations.AddField(
            model_name="product",
            name="lane_assist",
            field=models.BooleanField(default=False, help_text="Lane Assist"),
        ),
        migrations.AddField(
            model_name="product",
            name="traction_control",
            field=models.BooleanField(default=False, help_text="Traction Control"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Short descriptive name, e.g., '2019 Toyota Corolla LE'",
                max_length=255,
            ),
        ),
    ]
