# Generated by Django 4.2.23 on 2025-10-05 00:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_abs_product_airbags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="safety_features",
        ),
    ]
