# Generated by Django 4.2.23 on 2025-10-09 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mechanics", "0004_vehiclemake_parent_make_alter_vehiclemake_name_and_more"),
        ("products", "0006_remove_product_safety_features"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["-created_at", "ordering"]},
        ),
        migrations.CreateModel(
            name="ProductVehicleCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_from",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Starting year of compatibility (optional)",
                        null=True,
                    ),
                ),
                (
                    "year_to",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ending year of compatibility (optional)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional compatibility notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "make",
                    models.ForeignKey(
                        help_text="Vehicle make this product is compatible with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatible_products_by_make",
                        to="mechanics.vehiclemake",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific vehicle model (optional). If not specified, compatible with all models of the make.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatible_products_by_model",
                        to="mechanics.vehiclemake",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_compatibility",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["make__name", "model__name"],
                "indexes": [
                    models.Index(
                        fields=["product"], name="products_pr_product_60c07a_idx"
                    ),
                    models.Index(
                        fields=["make"], name="products_pr_make_id_1b8b5b_idx"
                    ),
                    models.Index(
                        fields=["model"], name="products_pr_model_i_305423_idx"
                    ),
                    models.Index(
                        fields=["year_from", "year_to"],
                        name="products_pr_year_fr_b9a1a4_idx",
                    ),
                ],
                "unique_together": {
                    ("product", "make", "model", "year_from", "year_to")
                },
            },
        ),
    ]
