# Generated by Django 4.2.23 on 2025-10-11 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mechanics", "0004_vehiclemake_parent_make_alter_vehiclemake_name_and_more"),
        ("products", "0007_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="productvehiclecompatibility",
            name="products_pr_year_fr_b9a1a4_idx",
        ),
        migrations.AlterUniqueTogether(
            name="productvehiclecompatibility",
            unique_together={("product", "make", "model")},
        ),
        migrations.RemoveField(
            model_name="productvehiclecompatibility",
            name="year_from",
        ),
        migrations.RemoveField(
            model_name="productvehiclecompatibility",
            name="year_to",
        ),
    ]
