# Generated by Django 4.2.23 on 2025-10-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0008_remove_productvehiclecompatibility_products_pr_year_fr_b9a1a4_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is a sub-category, select its name. Leave blank for namess.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="products.category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "parent_category")},
        ),
    ]
