# Generated by Django 4.2.23 on 2025-10-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_category_parent_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="body_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedan", "Sedan"),
                    ("suv", "SUV"),
                    ("hatchback", "Hatchback"),
                    ("coupe", "Coupe"),
                    ("truck", "Truck"),
                    ("van", "Van"),
                    ("convertible", "Convertible"),
                    ("wagon", "Wagon"),
                    ("other", "Other"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("petrol", "Petrol"),
                    ("diesel", "Diesel"),
                    ("electric", "Electric"),
                    ("hybrid", "Hybrid"),
                    ("lpg", "LPG"),
                    ("other", "Other"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="mileage_unit",
            field=models.CharField(
                blank=True,
                choices=[("km", "Kilometers"), ("mi", "Miles")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="transmission",
            field=models.CharField(
                blank=True,
                choices=[
                    ("automatic", "Automatic"),
                    ("manual", "Manual"),
                    ("cvt", "CVT"),
                    ("semi-automatic", "Semi-automatic"),
                    ("other", "Other"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
