# Generated by Django 4.2.23 on 2025-10-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_alter_product_body_type_alter_product_fuel_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="contact_info",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["contact_info"], name="products_pr_contact_1e22fc_idx"
            ),
        ),
    ]
