# Generated by Django 4.2.23 on 2026-03-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vin',
            field=models.CharField(blank=True, help_text='Vehicle Identification Number (VIN)', max_length=17, null=True, unique=True),
        ),
    ]
