# Generated by Django 4.2.23 on 2026-03-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_order_cancelled_at_order_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether the product is currently visible to customers",
            ),
        ),
    ]
