# Generated by Django 4.2.23 on 2026-04-02 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0014_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_hours', models.PositiveIntegerField(default=24, help_text='Duration of the bidding window in hours')),
                ('is_closed', models.BooleanField(default=False, help_text='Merchant can manually close bidding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_window', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bidding_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='products.biddingwindow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-amount', '-created_at'],
                'indexes': [models.Index(fields=['bidding_window'], name='products_bi_bidding_71b33c_idx'), models.Index(fields=['user'], name='products_bi_user_id_6f43e2_idx'), models.Index(fields=['status'], name='products_bi_status_9434fe_idx')],
            },
        ),
    ]
