# Generated by Django 4.2.23 on 2026-04-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_biddingwindow_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biddingwindow',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='biddingwindow',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, help_text='Duration of the bidding window in days'),
        ),
    ]
