# Generated by Django 4.2.23 on 2026-10-04 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0016_remove_biddingwindow_duration_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=1, help_text='Number of times this user/IP has viewed this product')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_viewed_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unique_views_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of unique viewers for this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of views this product has received'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['views_count'], name='products_pr_views_c_999ead_idx'),
        ),
        migrations.AddField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='products.product'),
        ),
        migrations.AddField(
            model_name='productview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product'], name='products_pr_product_e64eea_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['user'], name='products_pr_user_id_0ed8b1_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', 'user'], name='products_pr_product_823668_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', 'ip_address'], name='products_pr_product_377b90_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['last_viewed_at'], name='products_pr_last_vi_4e1e12_idx'),
        ),
    ]
